# Site settings
title: PEPPOL
email: peppol@tanglegence.com
description: A pan-European framework for public procurement
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://peppol.global" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
